# Generated by Django 4.0.2 on 2022-02-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('label', models.TextField()),
                ('poster', models.TextField()),
                ('total_products', models.IntegerField(default=0)),
                ('products_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('printed', 'Printed'), ('plain', 'Plain'), ('checks', 'Checks'), ('floral', 'Floral')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('title', models.CharField(choices=[('jeans', 'Jeans'), ('trousers', 'Trousers'), ('pants', 'Pants'), ('joggers', 'Joggers'), ('jogger_cargo', 'JoggerCargo'), ('cargo', 'Cargo'), ('lycra_pants', 'Lycra Pants')], max_length=100, verbose_name='Title')),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('MRP', models.IntegerField(default=0)),
                ('descriptions', models.TextField(null=True)),
                ('lg_image', models.TextField()),
                ('sm_image', models.TextField()),
                ('more_images', models.TextField()),
                ('is_out_of_stock', models.BooleanField(default=False)),
                ('available_qty', models.IntegerField()),
                ('sold_qty', models.IntegerField()),
                ('purchase_qty', models.IntegerField()),
                ('colors_availables', models.TextField(blank=True)),
                ('product_occasion', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('party', 'Party'), ('ethnic', 'Ethnic')], max_length=100, verbose_name='Occasion')),
                ('fabric', models.CharField(choices=[('cotton', 'Cotton'), ('teri-cotton', 'Teri-Cotton'), ('lycra', 'Lycra'), ('polyster', 'Polyster'), ('silk', 'Silk'), ('denim', 'Denim')], max_length=100, verbose_name='Fabric')),
                ('sleeve_type', models.CharField(choices=[('full-sleeve', 'Full Sleeve'), ('half-sleeve', 'Half Sleeve'), ('3/4-sleeve', '3/4 Sleeve')], max_length=100, verbose_name='Sleeve Length')),
                ('fitting_type', models.CharField(choices=[('slim', 'Slim'), ('comform', 'Comfort'), ('loose', 'Loose'), ('bomber', 'Bomber')], max_length=100, verbose_name='Fitting Type')),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.brand')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.productcategory')),
                ('pattern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pattern')),
            ],
        ),
    ]
