# Generated by Django 4.0.2 on 2022-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_occasion_alter_product_product_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Occasion Title'),
        ),
    ]
