# Generated by Django 4.0.2 on 2022-02-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_occasion_slug_alter_occasion_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_occasion',
            new_name='occasion_id',
        ),
    ]
