# Generated by Django 4.0.2 on 2022-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_product_occasion_product_occasion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
