# Generated by Django 4.0.2 on 2022-02-25 07:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_size',
            field=models.CharField(default=32, help_text='Enter size seperated with commans.', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(default='a', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='slug',
            field=models.CharField(default='a', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='title',
            field=models.CharField(choices=[('printed', 'Printed'), ('plain', 'Plain'), ('checks', 'Checks'), ('floral', 'Floral')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
