# Generated by Django 4.0.2 on 2022-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_product_sleeve_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='title',
            field=models.CharField(choices=[('printed', 'Printed'), ('plain', 'Plain'), ('checks', 'Checks'), ('floral', 'Floral'), ('ripped', 'Ripped')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fitting_type',
            field=models.CharField(choices=[('slim', 'Slim'), ('comform', 'Comfort'), ('loose', 'Loose'), ('bomber', 'Bomber'), ('none', None)], max_length=100, verbose_name='Fitting Type'),
        ),
    ]
