# Generated by Django 4.0.2 on 2022-02-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_pattern_title_alter_product_fitting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='title',
            field=models.CharField(choices=[('Printed', 'Printed'), ('Plain', 'Plain'), ('Checks', 'Checks'), ('Floral', 'Floral'), ('Ripped', 'Ripped')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Teri-cotton', 'Teri-Cotton'), ('Lycra', 'Lycra'), ('Polyster', 'Polyster'), ('Silk', 'Silk'), ('Denim', 'Denim')], max_length=100, verbose_name='Fabric'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fitting_type',
            field=models.CharField(choices=[('Slim', 'Slim'), ('Comform', 'Comfort'), ('Loose', 'Loose'), ('Bomber', 'Bomber'), ('None', None)], max_length=100, verbose_name='Fitting Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sleeve_type',
            field=models.CharField(choices=[('Full-sleeve', 'Full Sleeve'), ('Half-sleeve', 'Half Sleeve'), ('3/4-sleeve', '3/4 Sleeve'), ('None', 'None')], max_length=100, verbose_name='Sleeve Length'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Pants', 'Pants'), ('Joggers', 'Joggers'), ('Jogger_cargo', 'JoggerCargo'), ('Cargo', 'Cargo'), ('Lycra_pants', 'Lycra Pants')], max_length=100, verbose_name='Title'),
        ),
    ]
