# Generated by Django 4.0.2 on 2022-02-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_shipping_address_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
