# Generated by Django 4.0.2 on 2022-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_orders_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.CharField(max_length=255)),
                ('ordered_color', models.CharField(max_length=255, null=True)),
                ('ordered_product_image', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_detail',
            field=models.ManyToManyField(to='website.Product_OrderDetails'),
        ),
    ]
