# Generated by Django 4.0.2 on 2022-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_product_orderdetails_remove_orders_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orderdetails',
            name='item_price',
            field=models.FloatField(default=0),
        ),
    ]
