# Generated by Django 4.0.2 on 2022-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_product_orderdetails_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orderdetails',
            name='discount_amt',
            field=models.FloatField(default=0),
        ),
    ]
