# Generated by Django 4.0.2 on 2022-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_product_orderdetails_ordered_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_orderdetails',
            name='total_after_discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product_orderdetails',
            name='total_before_discount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
