# Generated by Django 4.0.2 on 2022-02-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_product_orderdetails_total_after_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_orderdetails',
            options={'verbose_name_plural': 'Product_OrderDetails'},
        ),
    ]
