# Generated by Django 4.0.2 on 2022-03-01 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_product_orderdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='gross_amt',
            field=models.FloatField(default=0, verbose_name='Gross Order Total'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.date(2022, 3, 1)),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping',
            field=models.IntegerField(default=0, verbose_name='Shipping Charges'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.shipping_address'),
        ),
        migrations.AddField(
            model_name='orders',
            name='slug',
            field=models.SlugField(default='a', unique=True),
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Your Active Address'),
        ),
    ]
