# Generated by Django 4.0.2 on 2022-03-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_orders_gross_amt_orders_order_confirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
