# Generated by Django 4.0.2 on 2022-03-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_orders_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orderdetails',
            name='product_slug',
        ),
        migrations.AddField(
            model_name='product_orderdetails',
            name='product_slug',
            field=models.ManyToManyField(to='website.Product'),
        ),
    ]
