# Generated by Django 4.0.2 on 2022-03-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_product_orderdetails_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orderdetails',
            name='product_slug',
        ),
        migrations.AddField(
            model_name='product_orderdetails',
            name='product_slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
    ]
