# Generated by Django 4.0.2 on 2022-03-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_product_orderdetails_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_orderdetails',
            name='ordered_qty',
            field=models.FloatField(default=0),
        ),
    ]
