# Generated by Django 4.0.2 on 2022-03-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_product_orderdetails_ordered_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_orderdetails',
            name='discount_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_orderdetails',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_orderdetails',
            name='ordered_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_orderdetails',
            name='total_after_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_orderdetails',
            name='total_before_discount',
            field=models.IntegerField(default=0),
        ),
    ]
