# Generated by Django 4.0.2 on 2022-03-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_product_orderdetails_discount_amt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_orderdetails',
            old_name='total_after_discount',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='product_orderdetails',
            name='total_before_discount',
        ),
    ]
