# Generated by Django 4.0.2 on 2022-03-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_rename_total_after_discount_product_orderdetails_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_orderdetails',
            old_name='product_slug',
            new_name='product_id',
        ),
    ]
