# Generated by Django 4.0.2 on 2022-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_rename_product_slug_product_orderdetails_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orderdetails',
            name='discount_amt',
        ),
        migrations.AlterField(
            model_name='product_orderdetails',
            name='item_price',
            field=models.IntegerField(default=0, verbose_name='Price After Discount'),
        ),
    ]
