# Generated by Django 4.0.2 on 2022-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_product_orderdetails_discount_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_orderdetails',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
