# Generated by Django 4.0.2 on 2022-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_product_orderdetails_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orderdetails',
            name='item_price',
        ),
        migrations.AddField(
            model_name='product_orderdetails',
            name='MRP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_orderdetails',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product_orderdetails',
            name='final_price',
            field=models.IntegerField(default=0, verbose_name='Final Price(After discount)'),
        ),
        migrations.AlterField(
            model_name='product_orderdetails',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total (Before discount)'),
        ),
    ]
