# Generated by Django 4.0.2 on 2022-03-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_product_orderdetails_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_orderdetails',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='product_orderdetails',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total (SP * Qty)'),
        ),
    ]
