# Generated by Django 4.0.2 on 2022-03-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_product_orderdetails_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_address',
            name='landmark',
            field=models.TextField(null=True),
        ),
    ]
