# Generated by Django 4.0.2 on 2022-03-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_shipping_address_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_address',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
