# Generated by Django 4.0.2 on 2022-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_shipping_address_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
