# Generated by Django 4.0.2 on 2022-03-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_alter_occasion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
