# Generated by Django 4.0.2 on 2022-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_orders_order_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_address',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
