# Generated by Django 4.0.2 on 2022-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
