# Generated by Django 4.0.2 on 2022-03-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_alter_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Teri-cotton', 'Teri-Cotton'), ('Lycra', 'Lycra'), ('Polyster', 'Polyster'), ('Silk', 'Silk'), ('Denim', 'Denim'), ('t-shirts', 'T-Shirts')], max_length=100, verbose_name='Fabric'),
        ),
    ]
