# Generated by Django 4.0.2 on 2022-03-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_product_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabric',
            field=models.CharField(choices=[('Cotton', 'Cotton'), ('Teri-cotton', 'Teri-Cotton'), ('Lycra', 'Lycra'), ('Polyster', 'Polyster'), ('Silk', 'Silk'), ('Denim', 'Denim')], max_length=100, verbose_name='Fabric'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Pants', 'Pants'), ('Joggers', 'Joggers'), ('Jogger_cargo', 'JoggerCargo'), ('Cargo', 'Cargo'), ('Lycra_pants', 'Lycra Pants'), ('t-shirts', 'T-Shirts'), ('shirts', 'Shirts')], max_length=100, verbose_name='Title'),
        ),
    ]
