# Generated by Django 4.0.2 on 2022-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_alter_product_fabric_alter_productcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.FileField(max_length=254, upload_to=''),
        ),
    ]
