# Generated by Django 4.0.2 on 2022-03-05 12:15

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_remove_brand_poster_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(max_length=254, null=True, upload_to=website.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='image',
            field=models.FileField(max_length=254, null=True, upload_to=website.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(max_length=254, upload_to=website.models.path_and_rename),
        ),
    ]
