# Generated by Django 4.0.2 on 2022-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_alter_orders_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
